apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: keita-watnabe-pipeline-from-scratch-pipeline-run-
spec:
  pipelineRef:
    name: keita-watnabe-pipeline-from-scratch-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: keita-watnabe-pvc